steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK 6.x'
    inputs:
      packageType: sdk
      version: '6.x'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.sln'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore --configuration Release'
